CREATE TABLE hcilin (
  linseq           NUMBER(38,0) NOT NULL,
  linno            NUMBER(38,0) NULL,
  claseq           NUMBER(38,0) NOT NULL,
  clasub           NUMBER(38,0) NOT NULL,
  patseq           NUMBER(38,0) NULL,
  prvseq           NUMBER(38,0) DEFAULT NULL NULL,
  billtyp          VARCHAR2(3)  NULL,
  condtyp          VARCHAR2(1)  NULL,
  dos              DATE         NULL,
  edos             DATE         NULL,
  pos              VARCHAR2(2)  NULL,
  posx             VARCHAR2(10) NULL,
  tos              VARCHAR2(2)  NULL,
  tosx             VARCHAR2(10) NULL,
  prvgeo           VARCHAR2(3)  NULL,
  prvzip           VARCHAR2(3)  NULL,
  prvspec          VARCHAR2(2)  NULL,
  prvspecx         VARCHAR2(15) NULL,
  patsex           VARCHAR2(1)  NULL,
  patdob           DATE         NULL,
  patzip           VARCHAR2(5)  NULL,
  elgdate          DATE         NULL,
  inelgdt          DATE         NULL,
  dx1              VARCHAR2(7)  NULL,
  dx2              VARCHAR2(7)  NULL,
  dx3              VARCHAR2(7)  NULL,
  dx4              VARCHAR2(7)  NULL,
  dx5              VARCHAR2(7)  NULL,
  dx6              VARCHAR2(7)  NULL,
  dx7              VARCHAR2(7)  NULL,
  dx8              VARCHAR2(7)  NULL,
  dx9              VARCHAR2(7)  NULL,
  admitdx          VARCHAR2(7)  NULL,
  proctype         VARCHAR2(1)  NULL,
  proctypex        VARCHAR2(6)  NULL,
  proc             VARCHAR2(11) NULL,
  m1               VARCHAR2(2)  NULL,
  m1x              VARCHAR2(2)  NULL,
  m2               VARCHAR2(2)  NULL,
  m2x              VARCHAR2(2)  NULL,
  m3               VARCHAR2(2)  NULL,
  m3x              VARCHAR2(2)  NULL,
  revcode          VARCHAR2(4)  NULL,
  revcodetype      VARCHAR2(1)  NULL,
  ndc              VARCHAR2(11) NULL,
  ndctype          VARCHAR2(1)  NULL,
  rxstrength       NUMBER(38,0) NULL,
  units            NUMBER(38,0) NULL,
  billed           NUMBER(10,2) NULL,
  allowed          NUMBER(10,2) NULL,
  ppoamt           NUMBER(10,2) NULL,
  paid             NUMBER(10,2) NULL,
  deduct           NUMBER(10,2) NULL,
  coin             NUMBER(10,2) NULL,
  icd9proc1        VARCHAR2(7)  NULL,
  icd9proc2        VARCHAR2(7)  NULL,
  icd9proc3        VARCHAR2(7)  NULL,
  icd9proc4        VARCHAR2(7)  NULL,
  icd9proc5        VARCHAR2(7)  NULL,
  icd9proc6        VARCHAR2(7)  NULL,
  adjstatus        VARCHAR2(1)  NULL,
  cap              VARCHAR2(1)  NULL,
  network          VARCHAR2(1)  NULL,
  hcirun           DATE         NULL,
  toothno          VARCHAR2(2)  NULL,
  toothsurf        VARCHAR2(5)  NULL,
  oralcavity       VARCHAR2(2)  NULL,
  formtype         VARCHAR2(1)  DEFAULT 'H' NULL,
  skip_fraud_stats VARCHAR2(1)  NULL,
  procx            VARCHAR2(11) NULL,
  billtype         VARCHAR2(1)  NULL,
  created          DATE         DEFAULT sysdate NULL,
  last_updated     DATE         DEFAULT sysdate NULL,
  dx1_ind          VARCHAR2(2)  DEFAULT '09' NULL,
  dx2_ind          VARCHAR2(2)  DEFAULT '09' NULL,
  dx3_ind          VARCHAR2(2)  DEFAULT '09' NULL,
  dx4_ind          VARCHAR2(2)  DEFAULT '09' NULL,
  dx5_ind          VARCHAR2(2)  DEFAULT '09' NULL,
  dx6_ind          VARCHAR2(2)  DEFAULT '09' NULL,
  dx7_ind          VARCHAR2(2)  DEFAULT '09' NULL,
  dx8_ind          VARCHAR2(2)  DEFAULT '09' NULL,
  dx9_ind          VARCHAR2(2)  DEFAULT '09' NULL,
  admitdx_ind      VARCHAR2(2)  DEFAULT '09' NULL,
  icd9proc1_ind    VARCHAR2(2)  DEFAULT '09' NULL,
  icd9proc2_ind    VARCHAR2(2)  DEFAULT '09' NULL,
  icd9proc3_ind    VARCHAR2(2)  DEFAULT '09' NULL,
  icd9proc4_ind    VARCHAR2(2)  DEFAULT '09' NULL,
  icd9proc5_ind    VARCHAR2(2)  DEFAULT '09' NULL,
  icd9proc6_ind    VARCHAR2(2)  DEFAULT '09' NULL,
  same             VARCHAR2(2)  DEFAULT '09' NULL
);

CREATE TABLE hciflag (
  flagseq           NUMBER(38,0)   NOT NULL,
  claseq            NUMBER(38,0)   NOT NULL,
  clasub            NUMBER(38,0)   NOT NULL,
  linseq            NUMBER(38,0)   NULL,
  linno             NUMBER(38,0)   NULL,
  editflg           VARCHAR2(4)    NULL,
  orderno           NUMBER(38,0)   NULL,
  review            VARCHAR2(1)    DEFAULT 'Y' NULL,
  editsrc           VARCHAR2(25)   NULL,
  paid              NUMBER(10,2)   NULL,
  deduct            NUMBER(10,2)   NULL,
  sugpaid           NUMBER(10,2)   NULL,
  savings           NUMBER(10,2)   NULL,
  topflag           VARCHAR2(1)    DEFAULT 'F' NULL,
  issav             VARCHAR2(1)    NULL,
  trigclaseq        NUMBER(38,0)   NULL,
  trigclasub        NUMBER(38,0)   NULL,
  triglinseq        NUMBER(38,0)   NULL,
  triglinno         NUMBER(38,0)   NULL,
  sugproc           VARCHAR2(5)    NULL,
  comments          VARCHAR2(1000) NULL,
  override          VARCHAR2(1)    DEFAULT 'F' NULL,
  deleted           VARCHAR2(1)    DEFAULT 'N' NULL,
  prepep            VARCHAR2(100)  NULL,
  hcidone           VARCHAR2(1)    DEFAULT 'F' NULL,
  hcisugpaid        NUMBER(10,2)   NULL,
  hcisugdate        DATE           NULL,
  clidone           VARCHAR2(1)    DEFAULT 'F' NULL,
  clisugpaid        NUMBER(10,2)   NULL,
  clisugdate        DATE           NULL,
  edittype          VARCHAR2(1)    NULL,
  billed            NUMBER(10,2)   NULL,
  repriceamt        NUMBER(10,2)   NULL,
  repricesav        NUMBER(10,2)   NULL,
  network           VARCHAR2(30)   NULL,
  drg_code          VARCHAR2(3)    NULL,
  dx                VARCHAR2(7)    NULL,
  icd9proc          VARCHAR2(7)    NULL,
  rec_code          VARCHAR2(12)   NULL,
  client_review_flg VARCHAR2(1)    DEFAULT 'Y' NULL,
  rule_seq          NUMBER(38,0)   DEFAULT -1 NULL,
  created           DATE           DEFAULT sysdate NULL,
  last_updated      DATE           DEFAULT sysdate NULL,
  sugunits          NUMBER(10,0)   DEFAULT 0 NULL,
  rule_data_1       VARCHAR2(100)  NULL,
  rule_data_2       VARCHAR2(100)  NULL,
  rule_data_3       VARCHAR2(100)  NULL,
  sub_product       VARCHAR2(1)    DEFAULT 'V' NULL,
  dx_ind            VARCHAR2(2)    DEFAULT '09' NULL,
  icd9proc_ind      VARCHAR2(2)    DEFAULT '09' NULL
);

CREATE TABLE claims (
  hcilinseq                      NUMBER        NOT NULL,
  hciclaseq                      NUMBER        NULL,
  hciclasub                      NUMBER        NULL,
  hciadjstatus                   VARCHAR2(1)   NULL,
  hcirun                         DATE          NULL,
  hcidos                         DATE          NULL,
  hcifile                        VARCHAR2(50)  NULL,
  hcivoid                        DATE          NULL,
  line_of_business               VARCHAR2(6)   NULL,
  claim_number                   VARCHAR2(20)  NULL,
  line_number                    VARCHAR2(4)   NULL,
  member_id                      VARCHAR2(12)  NULL,
  patient_id                     VARCHAR2(18)  NULL,
  patient_first_name             VARCHAR2(26)  NULL,
  patient_last_name              VARCHAR2(36)  NULL,
  patient_middle_init            VARCHAR2(26)  NULL,
  patient_adddress1              VARCHAR2(36)  NULL,
  patient_adddress2              VARCHAR2(36)  NULL,
  patient_city                   VARCHAR2(24)  NULL,
  patient_state                  VARCHAR2(2)   NULL,
  patient_zip                    VARCHAR2(10)  NULL,
  patient_dob                    VARCHAR2(8)   NULL,
  patient_sex                    VARCHAR2(2)   NULL,
  relation                       VARCHAR2(2)   NULL,
  primary_coverage_ind           VARCHAR2(1)   NULL,
  primary_coverage_num           VARCHAR2(3)   NULL,
  primary_coverage_name          VARCHAR2(30)  NULL,
  provider_tax_id                VARCHAR2(10)  NULL,
  rendering_provider_addr1       VARCHAR2(36)  NULL,
  rendering_provider_addr2       VARCHAR2(36)  NULL,
  rendering_provider_city        VARCHAR2(24)  NULL,
  rendering_provider_state       VARCHAR2(2)   NULL,
  rendering_provider_zip         VARCHAR2(10)  NULL,
  rendering_provider_npi         VARCHAR2(12)  NULL,
  rendering_provider_par_status  VARCHAR2(2)   NULL,
  provider_specialty_code        VARCHAR2(2)   NULL,
  pay_to_provider_addr1          VARCHAR2(36)  NULL,
  pay_to_provider_addr2          VARCHAR2(36)  NULL,
  pay_to_provider_city           VARCHAR2(24)  NULL,
  pay_to_provider_state          VARCHAR2(2)   NULL,
  pay_to_provider_zip            VARCHAR2(10)  NULL,
  pay_to_provider_npi            VARCHAR2(12)  NULL,
  amisys_provider_id             VARCHAR2(50)  NULL,
  referral_num                   VARCHAR2(12)  NULL,
  referral_type                  VARCHAR2(30)  NULL,
  provider_referral_num          VARCHAR2(17)  NULL,
  place_of_service               VARCHAR2(2)   NULL,
  type_of_bill                   VARCHAR2(4)   NULL,
  icd9_code                      VARCHAR2(8)   NULL,
  icd9_code2                     VARCHAR2(8)   NULL,
  icd9_code3                     VARCHAR2(8)   NULL,
  icd9_code4                     VARCHAR2(8)   NULL,
  icd9_code5                     VARCHAR2(8)   NULL,
  received_date                  VARCHAR2(8)   NULL,
  patient_account_num            VARCHAR2(20)  NULL,
  service_date_from              VARCHAR2(8)   NULL,
  service_date_to                VARCHAR2(8)   NULL,
  procedure_code                 VARCHAR2(12)  NULL,
  modifier1                      VARCHAR2(2)   NULL,
  modifier2                      VARCHAR2(2)   NULL,
  modifier3                      VARCHAR2(2)   NULL,
  modifier4                      VARCHAR2(2)   NULL,
  units                          VARCHAR2(9)   NULL,
  alt_procedure_code             VARCHAR2(12)  NULL,
  billed_amount                  VARCHAR2(10)  NULL,
  allowed_amount                 VARCHAR2(10)  NULL,
  adjustment_ind                 VARCHAR2(1)   NULL,
  original_claim_number          VARCHAR2(12)  NULL,
  original_claim_line_number     VARCHAR2(4)   NULL,
  ex_code                        VARCHAR2(12)  NULL,
  paid_amount_detail             VARCHAR2(10)  NULL,
  admit_code                     VARCHAR2(6)   NULL,
  discharge_code                 VARCHAR2(4)   NULL,
  claim_proc1                    VARCHAR2(12)  NULL,
  claim_proc2                    VARCHAR2(12)  NULL,
  claim_proc3                    VARCHAR2(12)  NULL,
  claim_proc4                    VARCHAR2(12)  NULL,
  claim_proc5                    VARCHAR2(12)  NULL,
  form_type                      VARCHAR2(6)   NULL,
  rendering_provider_last_name   VARCHAR2(36)  NULL,
  rendering_provider_first_name  VARCHAR2(36)  NULL,
  rendering_provider_middle_init VARCHAR2(1)   NULL,
  institution_name               VARCHAR2(36)  NULL,
  drg_code                       VARCHAR2(4)   NULL,
  admit_date                     VARCHAR2(8)   NULL,
  discharge_date                 VARCHAR2(8)   NULL,
  plan_code                      VARCHAR2(4)   NULL,
  servicing_prov_number          VARCHAR2(12)  NULL,
  transaction_type               VARCHAR2(1)   NULL,
  transaction_status             VARCHAR2(1)   NULL,
  date_of_remit_ccyymmdd         VARCHAR2(8)   NULL,
  former_tcn                     VARCHAR2(20)  NULL,
  claim_unit_vists_days          VARCHAR2(8)   NULL,
  claim_from_dos_ccyymmdd        VARCHAR2(8)   NULL,
  claim_thru_dos_ccyymmdd        VARCHAR2(8)   NULL,
  nature_hsp_admission           VARCHAR2(2)   NULL,
  provider_type                  VARCHAR2(2)   NULL,
  referring_provider_npi         VARCHAR2(10)  NULL,
  centene_referring_prov_nbr     VARCHAR2(12)  NULL,
  centene_referring_aff_nbr      VARCHAR2(4)   NULL,
  billed_amount_header           VARCHAR2(10)  NULL,
  billed_amount_net_header       VARCHAR2(10)  NULL,
  paid_amount_header             VARCHAR2(10)  NULL,
  drg_allowed_amount_header      VARCHAR2(12)  NULL,
  principal_procedure_code       VARCHAR2(12)  NULL,
  principal_proc_type            VARCHAR2(1)   NULL,
  principal_proc_type_2          VARCHAR2(1)   NULL,
  src_line_item_dtl_cnt          VARCHAR2(2)   NULL,
  resolution                     VARCHAR2(2)   NULL,
  revenue_code                   VARCHAR2(4)   NULL,
  billed_amount_net_detail       VARCHAR2(10)  NULL,
  other_ins_paid_detail          VARCHAR2(10)  NULL,
  claim_status                   VARCHAR2(2)   NULL,
  claim_type                     VARCHAR2(2)   NULL,
  form_type1                     VARCHAR2(6)   NULL,
  facility_type                  VARCHAR2(1)   NULL,
  bill_class                     VARCHAR2(1)   NULL,
  occurance                      VARCHAR2(1)   NULL,
  source_admission               VARCHAR2(2)   NULL,
  admit_dx_code                  VARCHAR2(8)   NULL,
  tpp_amt                        VARCHAR2(10)  NULL,
  tpp_allow_amt                  VARCHAR2(10)  NULL,
  tp_stat                        VARCHAR2(4)   NULL,
  allow_benefit_amt              VARCHAR2(12)  NULL,
  centene_plan_code              VARCHAR2(2)   NULL,
  centene_division_code          VARCHAR2(10)  NULL,
  plan_state_code                VARCHAR2(8)   NULL,
  payto_code                     VARCHAR2(2)   NULL,
  poa_ind1                       VARCHAR2(1)   NULL,
  poa_ind2                       VARCHAR2(1)   NULL,
  poa_ind3                       VARCHAR2(1)   NULL,
  poa_ind4                       VARCHAR2(1)   NULL,
  poa_ind5                       VARCHAR2(1)   NULL,
  occurance_code_1               VARCHAR2(2)   NULL,
  occurance_date_1               VARCHAR2(8)   NULL,
  value_code_1                   VARCHAR2(2)   NULL,
  value_amt_1                    VARCHAR2(11)  NULL,
  occurance_code_2               VARCHAR2(2)   NULL,
  occurance_date_2               VARCHAR2(8)   NULL,
  value_code_2                   VARCHAR2(2)   NULL,
  value_amt_2                    VARCHAR2(11)  NULL,
  occurance_code_3               VARCHAR2(2)   NULL,
  occurance_date_3               VARCHAR2(8)   NULL,
  value_code_3                   VARCHAR2(2)   NULL,
  value_amt_3                    VARCHAR2(11)  NULL,
  occurance_code_4               VARCHAR2(2)   NULL,
  occurance_date_4               VARCHAR2(8)   NULL,
  value_code_4                   VARCHAR2(2)   NULL,
  value_amt_4                    VARCHAR2(11)  NULL,
  occurance_code_5               VARCHAR2(2)   NULL,
  occurance_date_5               VARCHAR2(8)   NULL,
  value_code_5                   VARCHAR2(2)   NULL,
  value_amt_5                    VARCHAR2(11)  NULL,
  occurance_code_6               VARCHAR2(2)   NULL,
  occurance_date_6               VARCHAR2(8)   NULL,
  value_code_6                   VARCHAR2(2)   NULL,
  value_amt_6                    VARCHAR2(11)  NULL,
  occurance_code_7               VARCHAR2(2)   NULL,
  occurance_date_7               VARCHAR2(8)   NULL,
  value_code_7                   VARCHAR2(2)   NULL,
  value_amt_7                    VARCHAR2(11)  NULL,
  occurance_code_8               VARCHAR2(2)   NULL,
  occurance_date_8               VARCHAR2(8)   NULL,
  value_code_8                   VARCHAR2(2)   NULL,
  value_amt_8                    VARCHAR2(11)  NULL,
  icd_indicator                  VARCHAR2(2)   NULL,
  pay_to_provider_lastname       VARCHAR2(36)  NULL,
  pay_to_provider_firstname      VARCHAR2(36)  NULL,
  pay_to_institution_name        VARCHAR2(36)  NULL,
  pay_to_group_name              VARCHAR2(36)  NULL,
  business_unit                  VARCHAR2(2)   NULL,
  status_x                       VARCHAR2(2)   NULL,
  payclass                       VARCHAR2(8)   NULL,
  risk_population                VARCHAR2(200) NULL,
  pay_service                    VARCHAR2(200) NULL,
  benefit_package                VARCHAR2(200) NULL,
  bh_med_indicator               VARCHAR2(200) NULL,
  illness                        VARCHAR2(200) NULL,
  tpl_ind                        VARCHAR2(1)   NULL,
  wc_ind                         VARCHAR2(1)   NULL,
  member_relationship            VARCHAR2(1)   NULL,
  capitation_ind                 VARCHAR2(1)   NULL,
  benefit_pay_code               VARCHAR2(30)  NULL,
  accident_date                  VARCHAR2(8)   NULL,
  pmg_id                         VARCHAR2(4)   NULL,
  drg_ind                        VARCHAR2(1)   NULL,
  copay                          VARCHAR2(9)   NULL,
  coinsurance                    VARCHAR2(9)   NULL,
  deductible                     VARCHAR2(9)   NULL,
  medicare_allowed_amt_line      VARCHAR2(9)   NULL,
  category_code                  VARCHAR2(1)   NULL,
  rmc_code_at_date_of_service    VARCHAR2(2)   NULL,
  medical_record_number          VARCHAR2(30)  NULL,
  procedure_coding_method        VARCHAR2(4)   NULL,
  hospital_days                  VARCHAR2(12)  NULL,
  days_covered                   VARCHAR2(12)  NULL,
  ndc_number                     VARCHAR2(48)  NULL,
  member_referral_ind            VARCHAR2(1)   NULL,
  bank_code                      VARCHAR2(30)  NULL,
  admitting_provider             VARCHAR2(12)  NULL
);
